title: Syndromic Surveillance Tools
description: A collection of R packages and code to support syndromic surveillance data visualization.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions    
